services:
  - type: web
    name: careercast-resume-analyzer
    env: python
    buildCommand: "npm --prefix frontend install && npm --prefix frontend run build && python -m pip install -r requirements.txt && python backend/train_model.py"
    startCommand: "gunicorn backend.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
